/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.bank.gui;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import com.mycompany.bank.db.BidService;
/**
 *
 * @author ann
 */
public class ClientFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClientFrame
     */
    public ClientFrame(int id) {
        super("Окно клиента ID: "+ id);
        initComponents();
        setLocationRelativeTo(null);
        bidCredit.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            try {
                int sum=  Integer.parseInt(sumField.getText());
                    BidService.createNewBid(id, sum);
                    JOptionPane.showMessageDialog(null, "Заявка успешно отправлено, ждите ответа финансиста.");
                }
            catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "Введите сумму кредита.");
            }
        }});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bidCredit = new javax.swing.JButton();
        bidRestructr = new javax.swing.JButton();
        sumField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bidCredit.setText("Подать заявку на кредит");
        bidCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidCreditActionPerformed(evt);
            }
        });

        bidRestructr.setText("Подать заявку на реструктуризацию");

        jLabel1.setText("Введите сумму кредита (руб):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bidRestructr)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sumField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bidCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(sumField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(bidCredit)
                .addGap(27, 27, 27)
                .addComponent(bidRestructr)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bidCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bidCreditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bidCredit;
    private javax.swing.JButton bidRestructr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField sumField;
    // End of variables declaration//GEN-END:variables
}
